language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: jelWWWX6NnTHrU8WUZ0sgcTDJCLE9FLdwTwXZeAZzAdzOxNGKq4kN1p4gxFgkPr1M85/oxOUBiTjYtKEDE8HvjRAQ/p2agpKZUZSx9UJqHUBUdHgllXFsCnNvGWHcnYdRWL9CIPgbUEotlG6NlpJ4lWh+xKXfpAuhQfag/FvZxNYxVU7knImmWY1T+0TTaCZPf5kG1LMC0TlRvbIl8C/WFoHKcvvpyW/Mrf/MVf2Vw2r2J30sPzgVrIEdd84ICQnitRJ/7AWMccjkrOLnhzygqBMziY58EbhcFnSarDbLZrHfO9H7HUu4q0+1zwrKeDQ+Fn79F6uU0c4AxqCvzo3HbtGdkAoPoVj9CDNqpwu4kakqFcOdFBCw6getdG8RMdKGhO2wzs2iba83071ZgMWqc7HTi8CmfAmtRq51fC0YV7A2dVzXlb9Cn/RkAacbBa0qPy3VUaZHm7sQlhIawJJCRvmxYq8zTRgWKn7KpOXtSRYC7VktcDFsg/tDirWtrub4Uuydv+6q6vF57bUBuix2REnrHkfot+LSM07tvK4eFLxhIt428UzqG2qKifkhqvE7qFEyeP2FLbgDbwVfAul4QVCCxHIcQX0jPGL58ok0ttz8SN30c09gmmxIZ2iuCjgg7jZq4KNc0rN7G1EXJnygAZjXdk8ycqYbEK61vqy3Vw=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: HSSbQX/7khzJ5nT/DLx4ob8Qw8+OkPYZSR0KJsTUkoXHuYE98/bWbwk5KLm+Qbsz39IJUrF0UGLIr7sLex2r8Xz/5L4g1SGX2VEmsxOQedovhmuNzgfFHoWbuWS4L6hKRfLZLbqFS3c+0pjz4OHAYOaNrwUIzKuUHHnpMV2ZzmMqVexqETJoZIqzw83MH+iM4y3uKQBl2UFpUNRZeBCMjh7CJqHbFq2MG3y34xhFEm1sc95mBkJ3ePB+/nyRdhkosM7M7k0dkHfCAOJ9nutOdi323rtR+B3k9ZSZczeFNWECcKJQHV9qkJnLJQ3JqZFX5wCiUukQgZtESpH9jO7PFquHyuDbhrhVBllR5rKUUD9ff+qByXPr2/jyB5SV2qBleG0c2CEYbzthPyQeK4mp3iCImtwNTEQqhe79zpdPptXGza0SNAr9Cic0mqTOblYS0i/+oiSBKeF/xxJtNw7V1hXXxEmsb3ac5oTZw0WqW1MD1kTO1mlwvgi6tXq4odu20Rhg4yhadWGD6p+Q6fPDZirFm9h3NOm3FTPo7ae1iZ9v0jeSJTQYvGMkWDdkIUil+Ql/Qh6udM3vwfoYbIU/JW/NWNpDiLTqNwuctkOtmWrs8VIuhHAx2FjH3LskG2N2/aXelqpAhpkLcA0SI4oR5JImCP8V3vYaQsyCWbtzUyA=
    on:
      tags: true
